# Application Name
spring.application.name=scheduling-system

# Database Connection Settings (Spring DataSource)
spring.datasource.url=jdbc:mysql://localhost:3306/hotel_db
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate and JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# 'update' automatically updates the DB schema based on your Java Entities
spring.jpa.hibernate.ddl-auto=update

# Additional Settings for SQL Debugging
# Set to true to display executed SQL queries in the terminal
spring.jpa.show-sql=true